[package]
name = "bevy_mod_outline"
version = "0.4.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A mesh outlining plugin for Bevy."
readme = "README.md"
homepage = "https://github.com/komadori/bevy_mod_outline/"
repository = "https://github.com/komadori/bevy_mod_outline/"
keywords = ["gamedev", "bevy", "outline"]
categories = ["game-engines", "rendering"]

[dependencies]
bevy = { version = "0.10", default-features = false, features = [
    "bevy_asset",
    "bevy_render",
    "bevy_pbr",
    "bevy_core_pipeline",
] }
bitfield = "0.14"
interpolation = "0.2"
thiserror = "1.0"

[dev-dependencies]
bevy = { version = "0.10", default-features = false, features = [
    "animation",
    "bevy_gltf",
    "bevy_scene",
    "bevy_winit",
    "png",
    "x11",
] }
bevy_mod_gltf_patched = "0.2"

[features]
default = ["bevy_ui"]
bevy_ui = ["bevy/bevy_ui", "bevy/bevy_sprite", "bevy/bevy_text"]

[[example]]
name = "shapes"
path = "examples/shapes.rs"

[[example]]
name = "pieces"
path = "examples/pieces.rs"

[[example]]
name = "render_layers"
path = "examples/render_layers.rs"

[[example]]
name = "animated_fox"
path = "examples/animated_fox.rs"

[[example]]
name = "hollow"
path = "examples/hollow.rs"